STARTUP/urls.py
from django.urls import path,include
from django.contrib.auth.views import LogoutView
from .views import *
app_name = 'STARTUP'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about-us/', AboutView.as_view(), name='about'),
    path('services/', ServiesView.as_view(), name='services'),
    path('contact-us/', ContactView.as_view(), name='contact'),
    path('project/<slug:slug>/', Project_Done_DetailsView.as_view(), name='project_done_details'),
    path('all-categories/', CategoryView.as_view(), name='category'),
    
    
    path('accounts/', include('allauth.urls')),
    path('logout', LogoutView.as_view()),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('STARTUP.urls',namespace='startup')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/snippets/about_company.html
{% load static %}
<section class="section cta">
	<style>
		.cta
		{
			background: url("{{bg.home_page_img2.url}}") no-repeat;
			background-size: cover;
  			position: relative;
		}
	</style>
	<div class="container">
		<div class="row">
			<div class="col-lg-5">
				<div class="cta-content bg-white p-5 rounded">
					<h3 class="mb-4">Assurance Service In Software<span class="text-color-primary"> Testing</span> </h3>
					<p class="mb-30">An Independent Validation and Testing services from SISAR. Helps to reduce software development efforts</p>
					<a href="{% url 'startup:contact' %}" class="btn btn-main">Contact Us<i class="fa fa-angle-right ml-2"></i></a>
				</div>
			</div>
		</div>
	</div>
</section>

templates/snippets/about_work.html
{% load static %}
<section class="section about">
	<div class="container">
		<div class="row">
			<div class="col-lg-4 col-md-6 ">
				<div class="about-item mb-5 mb-lg-5">
					<div class="icon">
						<i class="ti-light-bulb"></i>
					</div>

					<div class="content">
						<h4 class="mt-3 mb-3">Custom Effective Software development</h4>
						<p class="mb-4">Saepe nulla praesentium eaque omnis perferendis a doloremque.</p>

						  
					</div>
				</div>
			</div>

			<div class="col-lg-4 col-md-6">
				<div class="about-item mb-5 mb-lg-5">
					<div class="icon">
						<i class="ti-panel"></i>
					</div>
					<div class="content">
						<h4 class="mt-3 mb-3">Analyse Your Expensees On Every Device</h4>
						<p class="mb-4">Saepe nulla praesentium eaque omnis perferendis a doloremque.</p>
						  
					</div>
				</div>
			</div>
			
			<div class="col-lg-4 col-md-6">
				<div class="about-item">
					<div class="icon">
						<i class="ti-headphone-alt"></i>
					</div>
					<div class="content">
						<h4 class="mt-3 mb-3">Creating a dedicated IT business growth</h4>
						<p class="mb-4">Saepe nulla praesentium eaque omnis perferendis a doloremque.</p>
						  
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

templates/snippets/footer.html
{% load static %}

<footer class="footer section">
	<div class="container">
		<div class="row">
			<div class="col-lg-3 mr-auto col-sm-6">
				<div class="widget mb-5 mb-lg-0">
					<div class="logo mb-4">
						<h3 style="color: #FF715B">{{com.title}}</h3>
					</div>
					<p style="text-align:justify;">{{com.description}}</p>
				</div>
			</div>
			<div class="col-lg-2 col-md-6 col-sm-6">
				<div class="widget mb-5 mb-lg-0">
					<h4 class="text-capitalize mb-4">Company</h4>

					<ul class="list-unstyled footer-menu lh-35">
						<li><a href="{% url 'startup:about' %}">About</a></li>
						<li><a href="{% url 'startup:services' %}">Services</a></li>
						<li><a href="#">Team</a></li>
						<li><a href="{% url 'startup:contact' %}">Contact</a></li>
					</ul>
				</div>
			</div>
			<div class="col-lg-3 col-md-6 col-sm-6">
				<div class="widget mb-5 mb-lg-0">
					<h4 class="text-capitalize mb-4">Support</h4>

					<ul class="list-unstyled footer-menu lh-35">
						<li><a href="#">Terms & Conditions</a></li>
						<li><a href="#">Privacy Policy</a></li>
						<li><a href="#">Support</a></li>
						<li><a href="#">FAQ</a></li>
					</ul>
				</div>
			</div>
			<div class="col-lg-3 col-md-6 col-sm-6">
				<div class="widget widget-contact mb-5 mb-lg-0">
					<h4 class="text-capitalize mb-4">Get in Touch</h4>
					<h6><a href="tel:{{com.phone_No}}" > <i class="ti-headphone-alt mr-3"></i>{{com.email}}</a></h6>
					<h6><a href="mailto:{{com.email}}" > <i class="ti-mobile mr-3"></i>{{com.phone_No}}</a></h6>

					<ul class="list-inline footer-socials mt-5">
						<li class="list-inline-item"><a href="{{com.fb_link}}" target="_blank"><i class="ti-facebook mr-2" style="color: #FF715B"></i></a></li>
						<li class="list-inline-item"><a href="{{com.tw_link}}" target="_blank"><i class="ti-twitter mr-2" style="color: #FF715B"></i></a></li>
						<li class="list-inline-item"><a href="{{com.ln_link}}" target="_blank"><i class="ti-linkedin mr-2 " style="color: #FF715B"></i></a></li>
					</ul>
				</div>
			</div>
		</div>
		
		<div class="footer-btm py-4 mt-5">
			<div class="row">
				<div class="col-lg-6">
					<div class="copyright">
						&copy; Copyright Reserved to <a class="text-color" style="color: #FF715B" href="/">{{com}}</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</footer>

templates/snippets/head.html
{% load static %}
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta name="description" content="Orbitor,business,company,agency,modern,bootstrap4,tech,software">
  <meta name="author" content="themefisher.com">
  <!-- Favicon -->
  <link rel="shortcut icon" type="image/x-icon" href="{% static '' %}{% static '' %}images/favicon.ico" />
  <!-- bootstrap.min css -->
  <link rel="stylesheet" href="{% static '' %}plugins/bootstrap/css/bootstrap.min.css">
  <!-- Icon Font Css -->
  <link rel="stylesheet" href="{% static '' %}plugins/themify/css/themify-icons.css">
  <link rel="stylesheet" href="{% static '' %}plugins/fontawesome/css/all.css">
  <link rel="stylesheet" href="{% static '' %}plugins/magnific-popup/dist/magnific-popup.css">
  <link rel="stylesheet" href="{% static '' %}plugins/animate-css/animate.css">
  <!-- Slick Slider  CSS -->
  <link rel="stylesheet" href="{% static '' %}plugins/slick-carousel/slick/slick.css">
  <link rel="stylesheet" href="{% static '' %}plugins/slick-carousel/slick/slick-theme.css">
  <!-- Main Stylesheet -->
 
  <link rel="stylesheet" href="{% static '' %}css/style.css">

templates/snippets/header.html
{% load static %}
<!-- Slider Start -->
<section class="banner d-flex align-items-center">
	<style>
		.banner{
			background:url("{{bg.home_page_img1.url}}") no-repeat 80% 50%;
  			background-size: cover;
		}
	</style>
	<div class="banner-img-part"></div>
	<div class="container">
		<div class="row">
			<div class="col-lg-10 col-md-12 col-xl-8">
				<div class="block">
					<span class="text-uppercase text-sm letter-spacing ">The most powerful Solution</span>
					<h1 class="mb-3 mt-3">Digital experience with Orbitor</h1>
					<p class="mb-5">{{com.description}}</p>
					<a href="{% url 'startup:about' %}" class="btn btn-main">Learn more about {{com}}<i class="fa fa-angle-right ml-2"></i></a>
				</div>
			</div>
		</div>
	</div>
</section>

templates/snippets/job_categories.html
{% load static %}
<section class="section process">
	<div class="container">
		<div class="row align-items-center">
			<div class="col-lg-5">
				<div class="process-block pl-4">
					<span class="text-uppercase text-sm letter-spacing">Why choose us</span>
					<h2 class="mb-4 mt-3">We help you to make work easy</h2>
					<p class="mb-4">{{com.description|slice:":150"}}</p>
				</div>
			</div>

			<div class="col-lg-7 col-xs-12 col-md-12">
				<div class="row">
					
					{% for cat  , icon in cat_and_icon %}
					<div class="col-lg-6 col-md-6 col-sm-6 mb-5">
						<div class="icon-block text-center mb-4 mb-lg-0">
							<i class={{icon}}></i>
							<h5>{{cat}}</h5>
						</div>
					</div>
					{% endfor %}
				</div>
			</div>	
		</div> 
	</div>
</section>

templates/snippets/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg py-4 navigation header-padding " id="navbar">
	<div class="container-fluid">
		<a class="navbar-brand" href="index.html">
		{% comment %} <img src="{% static '' %}images/logo.png" alt="" class="img-fluid"> {% endcomment %}
		<h2><span style="color:crimson">Soft</span><span>Com</span></h2>
		</a>

		<button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
		<span class="fa fa-bars"></span>
		</button>
	
		<div class="collapse navbar-collapse text-center" id="navbarsExample09">
		<ul class="navbar-nav m-auto">
			<li class="nav-item active">
			<a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
			</li>
			<li class="nav-item"><a class="nav-link" href="{% url 'startup:about' %}">About</a></li>
			<li class="nav-item"><a class="nav-link" href="{% url 'startup:services' %}">Services</a></li>
			<li class="nav-item "><a class="nav-link" href="{% url 'startup:category' %}">Job Categories</a></li>
			<li class="nav-item"><a class="nav-link" href="{% url 'startup:contact' %}">Contact</a></li>
		</ul>
		</div>
	</div>
</nav>

templates/snippets/navbar_secondary.html
{% load static %}
<nav class="navbar navbar-expand-lg  py-4 navigation header-padding nav-text-white" id="navbar">
	<div class="container-fluid">
		<a class="navbar-brand" href="index.html">
		{% comment %} <img src="{% static '' %}images/logo-w.png" alt="" class="img-fluid hidden-logo">
		<img src="{% static '' %}images/logo.png" alt="" class="img-fluid mobile-logo"> {% endcomment %}
		<h2><span style="color:crimson">Soft</span><span style="color: white">Com</span></h2>
		</a>

		<button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
		<span class="fa fa-bars"></span>
		</button>
	
		<div class="collapse navbar-collapse text-center" id="navbarsExample09">
		<ul class="navbar-nav m-auto">
			<li class="nav-item active">
			<a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
			</li>
			<li class="nav-item"><a class="nav-link" href="{% url 'startup:about' %}">About</a></li>
			<li class="nav-item"><a class="nav-link" href="{% url 'startup:services' %}">Services</a></li>
			<li class="nav-item "><a class="nav-link" href="{% url 'startup:category' %}">Job Categories</a></li>
			<li class="nav-item"><a class="nav-link" href="{% url 'startup:contact' %}">Contact</a></li>
		</ul>
		</div>
	</div>
</nav>

templates/snippets/our_statistics.html
{% load static %}
<section class="section counter">
	<div class="container">
		<div class="row">
			<div class="col-lg-3 col-md-6 col-sm-6">
				<div class="counter-item text-center mb-5 mb-lg-0">
					<h2 class="mb-0"><span class="counter-stat font-weight-bold">{{statistics.project_done_no}}</span> +</h2>
					<p>Project Done</p>
				</div>
			</div>
			<div class="col-lg-3 col-md-6 col-sm-6">
				<div class="counter-item text-center mb-5 mb-lg-0">
					<h2 class="mb-0"><span class="counter-stat font-weight-bold">{{statistics.users_world_no}} </span>M </h2>
					<p>User Worldwide</p>
				</div>
			</div>
			<div class="col-lg-3 col-md-6 col-sm-6">
				<div class="counter-item text-center mb-5 mb-lg-0">
					<h2 class="mb-0"><span class="counter-stat font-weight-bold">{{statistics.avilable_countries_no}}</span></h2>
					<p>Availble Country</p>
				</div>
			</div>
			<div class="col-lg-3 col-md-6 col-sm-6">
				<div class="counter-item text-center">
					<h2 class="mb-0"><span class="counter-stat font-weight-bold">{{statistics.award_winners_no}}</span></h2>
					<p>Award Winner </p>
				</div>
			</div>
		</div>
	</div>
</section>

templates/snippets/projects_had_finished.html
{% load static %}
<section class="section portfolio pb-0">
	<div class="container">
		<div class="row">
			<div class="col-lg-8">
				<div class="heading">
					<h2 class="mb-4">We’ve Done Lot’s of Work, Let’s Check Some From Here</h2>
					<p>We have the best experts to elevate your business to the next level, try is and you will see! We have the best experts to elevate your </p>
				</div>
			</div>
		</div>
	</div>

	<div class="container-fluid">
		<div class="row portfolio-gallery">
			{% for pro in project_done|slice:"0:6"  %}
			<div class="col-lg-4 col-md-6">
				<div class="portflio-item position-relative mb-4">
					<a href="{% url 'startup:project_done_details' pro.slug %}">
						<img src="{{pro.image.url}}" alt="" class="img-fluid w-100">
						<div class="overlay-item"><i class="ti-link"></i></div>	
						<div class="portfolio-item-content">
							<h3 class="mb-0 text-white">{{pro.title}}</h3>
							<p class="text-white-50">{{pro.category}}</p>
						</div>
					</a>
				</div>
			</div>
			{% endfor %}
		</div>
	</div>
</section>

templates/snippets/scripts.html
{% load static %}
<!-- Main jQuery -->
<script src="{% static '' %}plugins/jquery/jquery.js"></script>
<script src="{% static '' %}js/contact.js"></script>
<!-- Bootstrap 4.3.2 -->
<script src="{% static '' %}plugins/bootstrap/js/popper.js"></script>
<script src="{% static '' %}plugins/bootstrap/js/bootstrap.min.js"></script>
<!--  Magnific Popup-->
<script src="{% static '' %}plugins/magnific-popup/dist/jquery.magnific-popup.min.js"></script>
<!-- Slick Slider -->
<script src="{% static '' %}plugins/slick-carousel/slick/slick.min.js"></script>
<!-- Counterup -->
<script src="{% static '' %}plugins/counterup/jquery.waypoints.min.js"></script>
<script src="{% static '' %}plugins/counterup/jquery.counterup.min.js"></script>
<!-- Google Map -->

<script src="{% static '' %}js/script.js"></script>